services:
  mongo:
    image: mongo:8
    container_name: realtime-voting-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - voting_mongo_data:/data/db

volumes:
  voting_mongo_data:
